### ISSUE TITLE
DrCyano's Lootable Bodies Request

### ISSUE THREAD

**Issue by trechetican** [DNSTechpack/DNS10-MC1.10.2#13]
DrCyano's Lootable Bodies. or some other Graves mod. i always liked Lootable Bodies as it seemed a little different

**Comment by robaimes** [comment]
Gravestones will be back don't worry :)

OpenBlocks was used before, so if that gets updated I'll be using that. If not, This will be a suitable replacement.

**Comment by trechetican** [comment]
if you want to be evil https://minecraft.curseforge.com/projects/souls

**Comment by robaimes** [comment]
I've decided against Lootable Bodies, because it has potential to cause issues with body placement.

However, **_[this](https://minecraft.curseforge.com/projects/graves)**_ is a suitable replacement, equivalent to the previous ones in 1.7.10 with a few added extras. It has been added to the XML. more updates and configs will follow shortly.
