### ISSUE TITLE
Mod Request

### ISSUE THREAD

**Issue by trechetican** [DNSTechpack/DNS10-MC1.10.2#16]
Quark: adds lots of little nice additions that can be very handy https://minecraft.curseforge.com/projects/quark 

Roots: a nice new Magical mod based on nature and infusion  https://minecraft.curseforge.com/projects/roots

EvilCraft: cos who doesn't want to be evil :yum:   https://minecraft.curseforge.com/projects/evilcraft

Bloodmoon: loved having a bloodmoon in the old packs but as far as i am aware random things doesn't add it anymore  https://minecraft.curseforge.com/projects/bloodmoon

Agricultural Expansion: have used it quite a nice balanced ore growth mod  https://minecraft.curseforge.com/projects/agricultural-expansion

**Comment by robaimes** [comment]
Quark has been added.

Still looking over others.

**Comment by oedbro** [comment]
If you chose to add bloodmoon, I would propose that you add it as an optional mod

**Comment by robaimes** [comment]
Should probably update this...

_Bloodmoon won't be back_ I'm afraid. Had many requests to remove it entirely, and personally I don't like it either. (I'm the most unlucky person ever and always get one for 4 nights in a row)

_Evilcraft won't be added_ either. For much the same reason as above, with more detail, the pack revolves around building your base up and automating everything and not about hardcore survival. It shouldn't be affected by unfortunate occurences etc.

_Argicultural Expansion may be added_ in the future as an optional mod to replace magical crops, but this will depend on cross-mod compatibility.

_Roots_ is much the same. _It may be added_ in a future update as an optional mod once more tech mods are included, or when Thaumcraft is out.

**Comment by ctacquet** [comment]
I propose to add Simply Jetpack to complete the redstone arsenal mod

**Comment by robaimes** [comment]
@RedFive59 You should open your own issue to request mods. Also, this is for DNS 1.10.2 not 1.7.10.

**Comment by MacDonagal** [comment]
Avarita for complex craft like creative energy cell, ...

**Comment by bpwhelan** [comment]
"Evilcraft won't be added either. For much the same reason as above, with more detail, the pack revolves around building your base up and automating everything and not about hardcore survival. It shouldn't be affected by unfortunate occurences etc."

Evilcraft does not in any way make survival harder.

"Argicultural Expansion may be added in the future as an optional mod to replace magical crops, but this will depend on cross-mod compatibility."

If you do decide to add something like this, I would like to recommend Mystical Agriculture instead, since it is QUITE a lot more balanced, looks a lot prettier, and is more complete/active.

https://minecraft.curseforge.com/projects/mystical-agriculture

Roots looks very cool though.

**Comment by robaimes** [comment]
The problem with mystical agriculture is that it is highly unoptimised. I have friends who have used it, and out have caused their FPS to drop substantially due to huge amounts of block updates.

Coincidentally, one of them may be making the mod on his own, but make it clean and more optimised.

Roots may still be added as optional.
