### ISSUE TITLE
[Mod Request] Recurrent Complex

### ISSUE THREAD

**Issue by Brandcraf06** [DNSTechpack/DNS10-MC1.10.2#18]
A mod that contains 150+ generated structures.
And we can create its own structures and trees !!, it's very good with biome o'plenty
https://mods.curse.com/mc-mods/minecraft/223150-recurrent-complex

**Comment by robaimes** [comment]
I don't think I'll be adding this to the main DNS Techpack - Simply due to the fact that it does not fit the theme. We're all about automation, technology and Rube Goldberg machines.

This adds a **LOT** of exploration which is great, but not the style of what would fit this pack. However, i will be making use of this mod in a hardcore adventure map I am planning on creating at a later date.
