### ISSUE TITLE
MOD REQUEST- TAIGA

### ISSUE THREAD

**Issue by definablefan4** [DNSTechpack/DNS10-MC1.10.2#35]
MOD REQUEST

1.10.2

Taiga
https://minecraft.curseforge.com/projects/taiga-tinkers-alloying-addon
TAIGA is an addon for tinkers construct. It aims to find new minable ores, new alloys and a bunch of new tinker traits for them.

**Comment by robaimes** [comment]
I like that it adds to tinkers, but I don't like how it lists **14 new ores** as a feature. That is *very much overkill* on worldgen.

I want to stay away from overkill worldgen like 1.7.10, otherwise it just because excessively tedious to go mining at all. I won't say it will never be added, I just don't like the prospect of 14 additional ores, even if some are in the nether and end.

**Comment by definablefan4** [comment]
I know what you mean about there being too many ores. I just thought it would revive tinkers a bit because at the moment tinkers isn't the best.
