### ISSUE TITLE
MOD REQUEST : advanced solar pannels, more bees

### ISSUE THREAD

**Issue by Feez2403** [DNSTechpack/DNS10-MC1.10.2#48]
MOD REQUEST
  
Advanced solar pannels mod is out for 1.10.2.
It's really hard to get iridium without this mod. and there are some other great stuff you can do.
-> https://minecraft.curseforge.com/projects/advanced-solar-panels/files/2344357

More bees would be great to add too. There isn't a lot of things we can do with the normal forestry mod.
-> https://minecraft.curseforge.com/projects/more-bees/files/2326123

Applied energistics could be great too. I played a while on a server and there wasn't any problem due to AE2. -> https://minecraft.curseforge.com/projects/applied-energistics-2/files/2362522

Thanks for your hard work  !

**Comment by robaimes** [comment]
Could you please edit your post and add the links to each mod? Thanks.

**Comment by robaimes** [comment]
**AE2 has been added since version 10.0.6.0.**

*More bees* is a good candidate for an addon, as presumably it would work nicely with Gendustry. I will consider this for next update.

Not so sure about *Advanced Solar Panels*. It is a good mod and nice features, but Compact Solars is nearly identical to this and we already have this included. I don't want to include 2 mods that do basically the same thing. In my opinion Compact Solars is the cleaner version. ASP gets messy and has some unnecessary content.

As *More Bees* has been mentioned in request #51 I will close this for cleanliness. Check there for updates :)
