### ISSUE TITLE
AbyssalCraft

### ISSUE THREAD

**Issue by Xyain** [DNSTechpack/DNS10-MC1.10.2#6]
request

**Comment by robaimes** [comment]
Judging by the mod description

> AbyssalCraft is a mod centered around exploration, but with a growing magic influence.

It doesn't look like a particularly good fit for DNS, as there is no mention of technology or automation. The other concerning factor is the additional 4 dimensions.

By all means add it to your own instance, but it is not something I am willing to support as an optional mod due to its theme.
